# Generated by Django 5.1.2 on 2024-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streaming_package',
            name='monthly_price_cents',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='streaming_package',
            name='monthly_price_yearly_subscription_cents',
            field=models.IntegerField(null=True),
        ),
    ]
