# Generated by Django 5.1.2 on 2024-11-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0003_clubs_competitions'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='competitions',
            new_name='lieges',
        ),
    ]
