# Generated by Django 5.1.2 on 2024-11-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0004_rename_competitions_lieges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streaming_package',
            old_name='monthly_price_yearly_subscription_cents',
            new_name='monthly_price_yearly_subscription_in_cents',
        ),
    ]
