# Generated by Django 5.1.2 on 2024-11-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0005_rename_monthly_price_yearly_subscription_cents_streaming_package_monthly_price_yearly_subscription_i'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubs',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
