# Generated by Django 5.1.2 on 2024-11-02 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0006_clubs_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieges',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
