# Generated by Django 5.1.2 on 2024-11-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0007_lieges_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=10000)),
                ('value', models.CharField(max_length=10000)),
            ],
        ),
    ]
