# Generated by Django 5.1.2 on 2024-12-28 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csvFileParser', '0008_db_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestStreamingProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_best_provider', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvFileParser.clubs')),
                ('streaming_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csvFileParser.streaming_package')),
            ],
        ),
    ]
